name: "Lint"

on:
  push:
    branches: [main,github-actions-test]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Linting
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: install dependencies [pip]
        run:  |
          pip install -e .[dev]
      - name : linting [black, isort, flake8]
        run: |
          black . --check --extend-exclude 'examples'
          isort --profile black --check .
          flake8 .
