name: "Test"

on:
  push:
    branches: [main,github-actions-test]
    paths-ignore:
    - 'docs/**'
    - 'README.md'
    - 'LICENSE.txt'
    - '.gitignore'

  pull_request:
    branches: [main]
    paths-ignore:
    - 'docs/**'
    - 'README.md'
    - 'LICENSE.txt'
    - '.gitignore'


jobs:

  pytest:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install main package
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -e .[full,test]
      - name: Run tests [pytest]
        run: |
          pytest --cov --cov-report=xml:coverage.xml
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
          fail_ci_if_error: false